# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Expense Management' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Segmentio', '~> 3.0'
  pod 'Charts'
  pod 'FontAwesome.swift'
  pod 'SVPinView', '~> 1.0'
  pod 'SnapKit'


  # Pods for Expense Management

  target 'Expense ManagementTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Expense ManagementUITests' do
    # Pods for testing
  end

end
